### ISSUE TITLE
Full Yolo Detect

### ISSUE THREAD

**Issue by Cbanyungong** [mjDelta/yolo2-keras#2]
Have you tried the full yolo for detecting or used the tiny yolo for other dataset ? I still find the confidences of the boxe are 0.5.

![default](https://user-images.githubusercontent.com/29659406/40910766-9bab68a2-681f-11e8-8789-eb291ff25bbb.jpg)

**Comment by mjDelta** [comment]
First, in the codes I uploaded yestoday, it works. Have you downloaded the latest codes and train it? Maybe you can try. And what's the obj_th value you have set in YOLO.predict(). I have set it to 0.5.
Second, I prepare to implement full yolo and other backends to compare their mAPs.
